const users = {
  data: [
    {
      user: 'ANPINA',
      email: 'antonio.pina@tvglobo.com.br',
      date_inclusion: '28/05/2019',
      date_change: '30/05/2019',
      rules: '01',
      status: 'ATIVO',
    },
    {
      user: 'CCHANG',
      email: 'ciro.chang@tvglobo.com.br',
      date_inclusion: '28/05/2019',
      date_change: '30/05/2019',
      rules: '01',
      status: 'ATIVO',
    },
    {
      user: 'TMARCAL',
      email: 'thiago.marcal@tvglobo.com.br',
      date_inclusion: '28/05/2019',
      date_change: '30/05/2019',
      rules: '01',
      status: 'ATIVO',
    },
    {
      user: 'ECGIANN',
      email: 'ecgiannotto@tvglobo.com.br',
      date_inclusion: '28/05/2019',
      date_change: '30/05/2019',
      rules: '01',
      status: 'ATIVO',
    },
    {
      user: 'YFERNAND',
      email: 'yuri.vasquez@tvglobo.com.br',
      date_inclusion: '28/05/2019',
      date_change: '30/05/2019',
      rules: '02',
      status: 'ATIVO',
    },
    {
      user: 'PLACERDA',
      email: 'pedro.soares.lacerda@tvglobo.com.br',
      date_inclusion: '28/05/2019',
      date_change: '30/05/2019',
      rules: '02',
      status: 'ATIVO',
    },
  ],
};
